name: Docker CI

on:
  release:
    types: [published]

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: vanderkast/godville-spy

jobs:
  build_and_publish:
    name: Push Docker image to the Container registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Specify release tag
        run: TAG=${{ github.event.release.tag_name }} && echo "IMAGE_TAG=${TAG#v}" >> $GITHUB_ENV

      - name: Build and publish image
        run: make publish DOCKER_REGISTRY=$DOCKER_REGISTRY IMAGE_NAME=$IMAGE_NAME IMAGE_TAG=$IMAGE_TAG
